# Generated by Django 5.2.1 on 2025-06-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customeruser_role_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='skillset',
            field=models.CharField(max_length=200),
        ),
    ]
